### ISSUE TITLE
Setting the temporary folder for Sample doesn't work

### ISSUE THREAD

**Issue by bmuschko** [gradle/exemplar#40]
### Expected Behavior

A temporary folder can be provided to `Sample` as root directory.

### Current Behavior

The temporary isn't initialized yet when the `Rule` for the `Sample` kicks in. You will receive the following exception:

```
java.lang.IllegalStateException: the temporary folder has not yet been created
	at org.junit.rules.TemporaryFolder.getRoot(TemporaryFolder.java:145)
	at org.junit.rules.TemporaryFolder.newFolder(TemporaryFolder.java:94)
	at org.junit.rules.TemporaryFolder.newFolder(TemporaryFolder.java:86)
	at org.gradle.samples.test.rule.Sample$2.getDir(Sample.java:74)
	at org.gradle.samples.test.rule.Sample.computeSampleDir(Sample.java:165)
	at org.gradle.samples.test.rule.Sample.getDir(Sample.java:158)
	at org.gradle.samples.test.rule.Sample$3.evaluate(Sample.java:138)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:39)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

### Context

Setting a temporary folder with any of the `into` methods.

```
@Rule
TemporaryFolder temporaryFolder = new TemporaryFolder()

@Rule
Sample sample = Sample.from("src/docs/samples").into(temporaryFolder)
```

### Steps to Reproduce (for bugs)

See example above.

**Comment by eriwen** [comment]
Please use a `RuleChain`:

```
        public TemporaryFolder temporaryFolder = new TemporaryFolder()
        public Sample sample = Sample.from("src/test/samples/gradle")
            .into(temporaryFolder)
            .withDefaultSample("basic-sample")

        @Rule
        public TestRule ruleChain = RuleChain.outerRule(temporaryFolder).around(sample)
```
